# Generated by Django 3.1.4 on 2020-12-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactBook', '0002_auto_20201231_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='information',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='information',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
